// Career content for Skills / Experience / Education.
// Source of truth: assets/Swayam_Mehta_Resume.pdf (updated September 2026).

const CAREER = {
  skillRows: [
    {
      id: "languages",
      label: "Languages",
      items: [
        { name: "Python", mark: "PY" },
        { name: "C++", mark: "C+" },
        { name: "C#", mark: "C#" },
        { name: "TypeScript", mark: "TS" },
        { name: "SQL", mark: "SQ" },
        { name: "Bash", mark: "SH" },
      ],
    },
    {
      id: "ai-gpu",
      label: "AI & GPU computing",
      items: [
        { name: "Agentic AI", mark: "AG" },
        { name: "LLM tool calling", mark: "LL" },
        { name: "RAG", mark: "RG" },
        { name: "PyTorch", mark: "PT" },
        { name: "CUDA", mark: "CU" },
        { name: "Ultralytics YOLO", mark: "YO" },
        { name: "OpenCV", mark: "CV" },
      ],
    },
    {
      id: "infra",
      label: "Infrastructure & DevOps",
      items: [
        { name: "Linux", mark: "LX" },
        { name: "Docker", mark: "DK" },
        { name: "Docker Compose", mark: "DC" },
        { name: "GitHub Actions", mark: "GH" },
        { name: "GHCR", mark: "CR" },
        { name: "Azure App Service", mark: "AZ" },
        { name: "CI / CD", mark: "CI" },
      ],
    },
    {
      id: "observe",
      label: "Monitoring & reliability",
      items: [
        { name: "Grafana", mark: "GF" },
        { name: "Loki", mark: "LK" },
        { name: "Tempo", mark: "TP" },
        { name: "OpenTelemetry", mark: "OT" },
        { name: "Sentry", mark: "SE" },
        { name: "Production troubleshooting", mark: "OPS" },
      ],
    },
    {
      id: "backend",
      label: "Backend & data",
      items: [
        { name: "ASP.NET Core", mark: "NET" },
        { name: "FastAPI", mark: "FA" },
        { name: "EF Core", mark: "EF" },
        { name: "PostgreSQL", mark: "PG" },
        { name: "SQL Server", mark: "SS" },
        { name: "REST APIs", mark: "API" },
        { name: "Hangfire", mark: "HF" },
      ],
    },
    {
      id: "frontend",
      label: "Frontend & testing",
      items: [
        { name: "React", mark: "RE" },
        { name: "Next.js", mark: "NX" },
        { name: "xUnit", mark: "XU" },
        { name: "pytest", mark: "PT" },
        { name: "Vitest", mark: "VT" },
        { name: "Playwright", mark: "PW" },
      ],
    },
    {
      id: "identity",
      label: "Identity & integration",
      items: [
        { name: "Entra ID", mark: "EN" },
        { name: "OAuth 2.0", mark: "OA" },
        { name: "MSAL", mark: "MS" },
        { name: "Microsoft Graph API", mark: "MG" },
      ],
    },
  ],
  certifications: [],
  experience: [
    {
      id: "mckim-creed",
      company: "McKim & Creed",
      role: "AI Specialist I",
      location: "Raleigh, NC",
      start: "April 2026",
      end: "Present",
      status: "active",
      url: null,
      logo: "assets/mckim-creed-logo.png",
      logoDark: "assets/mckim-creed-logo-dark.png",
      bullets: [
        "Built and deployed a project coordination platform for a 230-person engineering group using C#, ASP.NET Core, EF Core, PostgreSQL, and React/TypeScript; implemented background jobs and enterprise authentication.",
        "Owned containerized deployment and production operations across Linux and Azure using Docker Compose, GitHub Actions, and GHCR; implemented versioned image releases, a separate production promotion workflow, and migration from SQL Server to PostgreSQL.",
        "Implemented production observability using Grafana, Loki, Tempo, and a 32-panel dashboard; restored service during a disk-capacity outage, introduced log retention, and diagnosed DNS, TLS, and authentication incidents.",
        "Improved backend performance by reducing a scheduling endpoint’s response payload by approximately 95%, replacing an import that timed out at approximately 2,400 rows with a batched transaction, and introducing cache-first lookups for upstream data.",
        "Shipped production agentic AI using Anthropic API tool calling and a Python/FastAPI intent router to orchestrate specialized engineering tools; delivered firm-wide access with streaming responses, persisted conversations, and token-budget management.",
        "Released 11 versions of an electrical takeoff application using Python, FastAPI, OpenCV, and React/TypeScript; reduced repeat rendering from 78 seconds to 0.3 seconds and deduplication from 4.4 seconds to 17 milliseconds, and addressed data loss with version history, conflict detection, and crash recovery.",
        "Trained computer-vision models on an NVIDIA GPU using PyTorch/CUDA and Ultralytics YOLO for engineering-drawing analysis; built a containerized FastAPI GPU inference prototype with a 240-test regression suite.",
      ],
    },
    {
      id: "sam-ssam",
      company: "SAM Analytic Solutions",
      team: "SSAM Team",
      role: "Junior AI & Systems Engineer",
      location: "Raleigh, NC",
      start: "May 2024",
      end: "April 2026",
      status: "done",
      url: null,
      logo: "assets/sam-analytic-logo.png",
      logoDark: "assets/sam-analytic-logo-dark.png",
      bullets: [
        "Developed the SSAM platform for electric substations, integrating thermal/PTZ cameras, AI models, edge devices, and SCADA systems.",
        "Trained and deployed YOLOv8 models for wildlife detection and automated deterrence workflows.",
        "Built multi-threaded Python pipelines for RTSP streaming, frame processing, motion filtering, and GPU inference.",
        "Developed a Flask/MongoDB dashboard for live streams, thermal monitoring, detections, recordings, and event history.",
        "Implemented thermal zones, threshold alerts, heatmaps, and automated event logging for equipment monitoring.",
        "Integrated Modbus TCP, relays, NVRs, Raspberry Pi systems, and network cameras across lab and field deployments.",
        "Supported field deployment, troubleshooting, performance tuning, and validation across multiple utility substations.",
      ],
    },
  ],
  education: [
    {
      id: "uncc",
      school: "University of North Carolina at Charlotte",
      degree: "B.S. Computer Engineering — Machine Learning Concentration",
      minor: "Mathematics",
      start: "August 2020",
      end: "December 2024",
      status: "done",
    },
  ],
};
